# Generated by Django 3.0.2 on 2020-03-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
