# Generated by Django 3.0.2 on 2020-03-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0002_auto_20200323_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.ImageField(blank=True, default='nobody_m.original.jpg', upload_to='image/dp/'),
        ),
    ]
