# Generated by Django 3.0.2 on 2020-03-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0003_auto_20200327_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.ImageField(blank=True, default='sample_dp.jpg', upload_to='image/dp/'),
        ),
    ]
