# Generated by Django 3.0.2 on 2020-03-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0004_auto_20200327_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, default='image/cover/sample_cover.jpg', upload_to='image/cover/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.ImageField(blank=True, default='image/dp/sample_dp.jpg', upload_to='image/dp/'),
        ),
    ]
