# Generated by Django 3.0.2 on 2020-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0005_auto_20200327_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, default='cover/sample_cover.jpg', upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.ImageField(blank=True, default='dp/sample_dp.jpg', upload_to='dp/'),
        ),
    ]
