# Generated by Django 3.0.2 on 2020-03-28 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0006_auto_20200327_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datawork.User')),
            ],
        ),
    ]
