# Generated by Django 3.0.2 on 2020-03-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='datawork.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='datawork.User'),
        ),
    ]
